---
title: "Task2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```


```{r}
# read in the data
accounts = read_csv("data/accounts_analytical.csv")
head(accounts)
```



```{r}
# scatter plot of loan amount for each account
# get rid of missing values in loan amount
df = accounts %>% filter(!is.na(loan_amount))
p1 = ggplot(data=df, aes(x=account_id, y=loan_amount)) +
  geom_point(size = 0.05) + labs(title="Scatterplot of loan amount", 
         x="Account ID", y = "Loan Amount")

p1

```

```{r}
p2 = ggplot(df, aes(x=loan_amount)) + geom_histogram(color="black", fill="lightblue") + labs(title="Histogram of Loan Amount", 
         x="Loan Amount", y = "Count")
p2
```

The distribution of the loan amount is skewed to the right. 

```{r}
p3 = ggplot(df, aes(x=loan_default)) + geom_histogram(stat="count",color="black", fill="lightblue") + labs(title="Histogram of Loan Default", 
         x="Loan Defualt", y = "Count")
p3

```


Most loans are not default.   

```{r}
# distribution of loan status
p4 = ggplot(df, aes(x=loan_status)) + geom_histogram(stat="count",color="black", fill="lightblue") + labs(title="Histogram of Loan Status", 
         x="Loan Status", y = "Count")
p4

```


THe majority of the loans are current.   


```{r}
# distribution of loan term
p5 = ggplot(df, aes(x=loan_term)) + geom_histogram(stat="count",color="black", fill="lightblue") + labs(title="Histogram of Loan Term", 
         x="Loan Term", y = "Count")
p5


```

The duration of loans is nearly uniformly distributed.   


```{r}
p6 = ggplot(df, aes(x=loan_payment)) + geom_histogram(color="black", fill="lightblue") + labs(title="Histogram of Loan Payment", 
         x="Loan Payment", y = "Count")
p6

```

The loan payment variable is also slightly right-skewed.   

```{r}
p7 = ggplot(df, aes(x=loan_date)) + geom_histogram(color="black", fill="lightblue") + labs(title="Histogram of Loan Date", 
         x="Loan Date", y = "Count")
p7

```

The loan date variable is slightly left-skewed.   









































